name: CI

on: [pull_request, push]

jobs:
  type-check:
    name: Typecheck
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Install mypy
      run: pip install mypy
    - name: Typecheck
      run: mypy check.py
